alpine_task:
        container:
                image: alpine:latest
        install_script: apk add autoconf automake g++ gcc libusb-dev libtool linux-headers eudev-dev make musl-dev
        script:
                - ./bootstrap
                - ./configure || { cat config.log; exit 1; }
                - make
                - make install

freebsd_task:
        freebsd_instance:
                image_family: freebsd-14-3
        install_script:
                - pkg install -y
                  autoconf automake libiconv libtool pkgconf
        script:
                - ./bootstrap
                - ./configure || { cat config.log; exit 1; }
                - make
                - make install
