name: Checks
run-name: Code checks for ${{ github.ref_name }}

on: 
  workflow_dispatch:

jobs:
  coverity-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: src
    - name: Install dependencies
      run: brew install ninja
